[tool.isort]
profile = "black"

[tool.pyright]
reportInvalidTypeForm = false
reportMissingImports = false
reportMissingModuleSource = false
extraPaths = [
    "C:/Program Files/Blender Foundation/Blender 4.4/4.4/scripts/addons_core",
]
